### ISSUE TITLE
App crash at start on android 12.1

### ISSUE THREAD

**Issue by HugoRh** [NeoApplications/Neo-Backup#499]
**Description**
On a fresh install, the app crash directly
**Steps To Reproduce**
click on the app
4. Crash, Nothing happens ....

**Expected behavior**
just to start 

**log**
```
time: 1647105875608
msg: v3.b0: Protocol message contained an invalid tag (zero).
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.machiav3lli.backup/com.machiav3lli.backup.activities.SplashActivity}: v3.b0: Protocol message contained an invalid tag (zero).
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3707)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7865)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: v3.b0: Protocol message contained an invalid tag (zero).
	at v3.y.t(:7)
	at u3.c0.E(Unknown Source:2)
	at r3.a$b.b(:2)
	at r3.a$b.a(Unknown Source:11)
	at d.c.s(:17)
	at d.b.r(:1)
	at com.machiav3lli.backup.activities.SplashActivity.onCreate(Unknown Source:0)
	at android.app.Activity.performCreate(Activity.java:8054)
	at android.app.Activity.performCreate(Activity.java:8034)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1347)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
	... 12 more
```

**System Information(please complete the following information):**

- Device:  Redmi k20 pro
- Android Version: 12
- ROM: AOSP
- App's Version: 7

-----------------------------

**Additional Notes**

* If you're on the latest Test version(from the TG-Channel or Matrix-Room) please report there directly, not here.

* If you're on the latest github version:
  
  * Please read the [FAQ](https://github.com/machiav3lli/oandbackupx/blob/master/FAQ.md) first.
  * Please read all the open Issues. If one does match yours, leave a comment there if there's some extra information you can provide.

* If you're not on the latest github version. Update, then make sure that the bug is still there. If it's go further with reporting.

Thanks for reporting.

**Comment by machiav3lli** [comment]
You possibly mean 12L. It seems Jetpack Security library is still incompatible with the latest Android version.

**Comment by HugoRh** [comment]
Any idea how to workaround this one?
I got some similar error with google ting which I managed to workaround by reinstalling the app ( but it's not working with OandBackupX).
Thank !

**Comment by ashjas** [comment]
Hi, i have the same crash on startup, but differet logcat:
Android 12.1 
```
06-09 20:11:34.395 11418 11434 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 1110341; state: ENABLED
06-09 20:11:34.403 11418 11418 D h@7:g$a : Command(s) "/data/local/toybox" --version ended with -1
06-09 20:11:34.403 11418 11418 D h@1:g$a : Running Command: "/data/local/toybox"
06-09 20:11:34.403 11418 11418 D h@7:g$a : Command(s) "/data/local/toybox" ended with -1
06-09 20:11:34.404 11418 11418 D h@1:g$a : Running Command: "toybox" --version
06-09 20:11:34.404 11418 11418 D h@7:g$a : Command(s) "toybox" --version ended with -1
06-09 20:11:34.404 11418 11418 D h@1:g$a : Running Command: "toybox"
06-09 20:11:34.404 11418 11418 D h@7:g$a : Command(s) "toybox" ended with -1
06-09 20:11:34.404 11418 11418 D <init>@7:g: No more options for utilbox. Bailing out.
06-09 20:11:34.404 11418 11418 D AndroidRuntime: Shutting down VM
06-09 20:11:34.404 11418 11418 E AndroidRuntime: FATAL EXCEPTION: main
06-09 20:11:34.404 11418 11418 E AndroidRuntime: Process: com.machiav3lli.backup, PID: 11418
06-09 20:11:34.404 11418 11418 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.machiav3lli.backup.OABX: y7.g$e:
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6767)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at android.app.ActivityThread.access$1500(ActivityThread.java:256)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7870)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
06-09 20:11:34.404 11418 11418 E AndroidRuntime: Caused by: y7.g$e:
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at y7.g.<init>(:7)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at com.machiav3lli.backup.OABX.onCreate(:1)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1229)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6762)
06-09 20:11:34.404 11418 11418 E AndroidRuntime:        ... 9 more
06-09 20:11:34.406  1396 11444 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
06-09 20:11:34.406  1396  9305 W ActivityTaskManager:   Force finishing activity com.machiav3lli.backup/.activities.SplashActivity
06-09 20:11:34.408 11418 11418 I Process : Sending signal. PID: 11418 SIG: 9
06-09 20:11:34.409  1396  1487 I EventSequenceValidator: dec AccIntentStartedEvents to 1
06-09 20:11:34.417  1396  9305 I ActivityManager: Process com.machiav3lli.backup (pid 11418) has died: fg  TOP
06-09 20:11:34.421   682   682 I Zygote  : Process 11418 exited due to signal 9 (Killed)
06-09 20:11:34.422  1396  1503 I libprocessgroup: Successfully killed process cgroup uid 1110341 pid 11418 in 5ms
```

**Comment by hg42** [comment]
> Any idea how to workaround this one?

may be use v8?

**Comment by hg42** [comment]
> Hi, i have the same crash on startup, but differet logcat

as you already said yourself, it's **not** the same crash, but a very different...
So, this should be a separate issue.

You don't have a toybox on your system, which is weird, I think.
Why is it missing? toybox should be provided by any Android NB supports.
Also, NB cannot work without toybox. And yes we know busybox, but it's even more complicated with this.
