### ISSUE TITLE
[Bug] Errors when backing up to Nextcloud

### ISSUE THREAD

**Issue by Maxwell175** [NeoApplications/Neo-Backup#555]
**Description**
When backing up to Nextcloud (though SAF) I get various errors in the log and a mostly incomplete backup. I suspect these might be caused by the asynchronous nature of Nextcloud as files are not uploaded right away, and folders might not yet be available.

**Steps To Reproduce**

1. Setup Nextcloud app
2. Setup Neo Backup to save to a folder in Nextcloud
3. Run a backup of a few different apps.

**Expected behavior**
The backup to successfully complete.

**System Information(please complete the following information):**

- Device: Moto Z2 (nash)
- Android Version: 9
- ROM: (AOSP, MIUI, OOS...)  LineageOS
- App's Version: 8.0.2 and current main

**Logcat errors:**

```
I/genericBackupDataTarCmd@482:BackupAppAction: SHELL: su  -c sh "/data/user/0/com.machiav3lli.backup.debug/files/assets/tar.sh" create "toybox"  --exclude "/data/user/0/com.machiav3lli.backup.debug/files/assets/tar_EXCLUDE" --exclude "/data/user/0/com.machiav3lli.backup.debug/files/assets/tar_EXCLUDE_CACHE" "/data/user/0/com.android.internal.display.cutout.emulation.tall"
I/genericBackupDataTarCmd@503:BackupAppAction: Unknown id: "/data/user/0/com.machiav3lli.backup.debug/files/assets/tar.sh"
E/logException@138:LogsHandler$Companion: unexpected: {
    com.machiav3lli.backup.actions.BaseAppAction.ScriptException occurred on data backup: com.machiav3lli.backup.actions.BaseAppAction$ScriptException: Unknown id: "/data/user/0/com.machiav3lli.backup.debug/files/assets/tar.sh"
    }
    
    ScriptException
    Unknown id: "/data/user/0/com.machiav3lli.backup.debug/files/assets/tar.sh"
        at com.machiav3lli.backup.actions.BackupAppAction.genericBackupDataTarCmd(BackupAppAction.kt:504)
        at com.machiav3lli.backup.actions.BackupAppAction.genericBackupData(BackupAppAction.kt:539)
        at com.machiav3lli.backup.actions.BackupAppAction.backupData(BackupAppAction.kt:565)
        at com.machiav3lli.backup.actions.BackupAppAction.run(BackupAppAction.kt:137)
        at com.machiav3lli.backup.handler.BackupRestoreHelper.backup(BackupRestoreHelper.kt:86)
        at com.machiav3lli.backup.tasks.AppActionWork.doWork(AppActionWork.kt:168)
        at com.machiav3lli.backup.tasks.AppActionWork$doWork$1.invokeSuspend(Unknown Source:14)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
D/genericBackupDataTarCmd@512:BackupAppAction: Done compressing. Closing data.tar.gz
E/run@179:BackupAppAction: Backup failed due to BackupFailedException: com.machiav3lli.backup.actions.BaseAppAction.ScriptException occurred on data backup: com.machiav3lli.backup.actions.BaseAppAction$ScriptException: Unknown id: "/data/user/0/com.machiav3lli.backup.debug/files/assets/tar.sh"
```

```
E/logException@138:LogsHandler$Companion: unexpected: {
    content://org.nextcloud.documents/tree/1210686772%2F4/document/1210686772%2F2186
    }
    
    SecurityException
    Document 1210686772/2186 is not a descendant of 1210686772/4
        at android.os.Parcel.createException(Parcel.java:1950)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
        at android.content.ContentResolver.query(ContentResolver.java:803)
        at android.content.ContentResolver.query(ContentResolver.java:753)
        at android.content.ContentResolver.query(ContentResolver.java:711)
        at com.machiav3lli.backup.utils.UriUtilsKt.getName(UriUtils.kt:50)
        at com.machiav3lli.backup.items.StorageFile.getName(StorageFile.kt:154)
        at com.machiav3lli.backup.items.StorageFile.findFile(StorageFile.kt:297)
        at com.machiav3lli.backup.dbs.entity.Backup.getBackupInstanceFolder(Backup.kt:170)
        at com.machiav3lli.backup.items.Package.deleteBackup(Package.kt:255)
        at com.machiav3lli.backup.actions.BackupAppAction.run(BackupAppAction.kt:208)
        at com.machiav3lli.backup.handler.BackupRestoreHelper.backup(BackupRestoreHelper.kt:86)
        at com.machiav3lli.backup.tasks.AppActionWork.doWork(AppActionWork.kt:168)
        at com.machiav3lli.backup.tasks.AppActionWork$doWork$1.invokeSuspend(Unknown Source:14)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by hg42** [comment]
I never got nextcloud to work reliably (as SAF provider)

but the error you get, doesn't look related to what I experienced

the shell command calls a script, that is copied to the data directory into files/assets when NB is lauched and the file isn't the correct one (or doesn't exist):
```
SHELL: su  -c sh "/data/user/0/com.machiav3lli.backup.debug/files/assets/tar.sh" create "toybox"  ...
```

though I don't understand, why the message is about an "id", it doesn't look like a message from a shell ("sh"):
```
Unknown id: "/data/user/0/com.machiav3lli.backup.debug/files/assets/tar.sh"
```
the access is usually file based, so no "id" should be involved?

do you have another shell installed as sh?
which su do you use?

please add the output of

```
su --version
sh -v
```

you should check if the tar.sh exists in `<data>/files/assets` (and some other files, especially a `__version__` file)

please add a logcat (or log from the debug console) from around the start of NB.
It should show if it gets an exception while trying to copy those files:
```
cannot copy scripts to ${directory}
```
