### ISSUE TITLE
[Bug] SMS restore fails because of database version

### ISSUE THREAD

**Issue by outtaspes** [NeoApplications/Neo-Backup#584]
Hello,

**Description**
I made an SMS backup on an Android 11 device and tried to restore it on an Android 12 device. It fails with:

> **Errors occurred**
Can't downgrade database from version 68 to 67

**Steps To Reproduce**

0. Set SMS App as Neo Backup (both devices)
1. Backup on device 1 (Android 11)
2. Restore on device 2 (Android 12)
3. See error message above

**Expected behavior**
Restore works.

**System Information(please complete the following information):**

> Device(backup): Xiaomi Redmi 5 Plus
Android Version: 11
ROM: crDroid (LineageOS based)
App's Version: 8.0.2

> Device(restore): Xiaomi Redmi Note 11
Android Version: 12
ROM: SuperiorOS (AOSP based I think)
App's Version: 8.0.2

Kind regards,

spes

**Comment by hg42** [comment]
just to be sure, you are talking of the special backup?:

label: $ SMS/MMS JSON
package name: special.smsmms.json

I am asking, because the special package only stores a json file in the backup data, so at least this part should be independent from database versions (and It's the reason for using a portable json file).

I also didn't see a 67 or 68 in the sources that could have to do with databases.

So I assume, it may be caused by some automatic versioning of libraries.
Perhaps bound to the sdk version?
Since 8.0.0-alpha8 it's sdk32 (Andorid 12.1).
8.0.0-alpha7 was the last with sdk31 (Android 12).
Such a dependency would be bad...(no backward compatibility of the sdk in this case)

You could try 8.1.0-alpha1 pinned in the telegram group, just as a test. Though, if it's the sdk version, it will not change that incompatibility.

May be @dl200010 can say more...

**Comment by dl200010** [comment]
@hg42 Yes, it is developed to merge data in without issue. It does attempt to try to prevent duplicates, but that may be possible. So, no data should be lost, but could be duplicated.

The SMS/MMS JSON special reads from the SMS/MMS provider in Android. I personally did a backup on Android 11 (OxygenOS) and restore on Android 12 (OxygenOS).

@outtaspes Could you relay if it is the "$ SMS/MMS JSON" special ("special.smsmms.json") or if it is the "Phone Call/SMS Storage" ("com.android.providers.telephony")? I can see the "Phone Call/SMS Storage" having this issue. A screenshot of the error might help, or a captured logcat from a debug build.

**Comment by hg42** [comment]
@dl200010
I didn't look into the code, but I assume, you are doing the obvious, reading the json and using an api to merge with the system data, right?
I don't see how there can be a database involved.

@outtaspes
can you try to use another SMS backup app to backup and restore the sms', to test if the API works at all? eventually your new ROM has an issue with that?
Especially because a restore worked with A12 according to @dl200010 (assuming he used at least NB 8.0.0-alpha8 for the test).

**Comment by outtaspes** [comment]
@hg42 It's not the JSON itself I suppose, but the database for the SMS provider (com.android.providers.telephony) I think. Yeah, I can try another backup solution.  

Okay here is the logcat:
<details>

```
06-27 22:58:06.040 10420 10420 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
06-27 22:58:09.246 10420 10420 D h@1:g$a : Running Command: pm list users | "toybox" sed -nr 's/.*\{([0-9]+):.*/\1/p'
06-27 22:58:09.296 10420 10420 D h@7:g$a : Command(s) pm list users | "toybox" sed -nr 's/.*\{([0-9]+):.*/\1/p' ended with 0
06-27 22:58:11.372 10420 10500 I c@3:d   : Restoring: special.smsmms.json [$ SMS/MMS JSON]
06-27 22:58:11.372 10420 10500 D c@8:d   : pre-process package (to avoid file inconsistencies during backup etc.)
06-27 22:58:11.372 10420 10500 W f@6:d   : special.smsmms.json does not exist. Cannot preprocess!
06-27 22:58:11.373 10420 10500 I r@26:i  : Schedule{packageName=special.smsmms.json, appInfo=v7.g@62020a0, appUri=/tree/primary:OABX/document/primary:OABX/special.smsmms.json, storageStats=null, backupList=[Backup{backupDate=2022-06-26T15:41:28.573, hasApk=false, hasAppData=true, hasDevicesProtectedData=false, hasExternalData=false, hasObbData=false, hasMediaData=false, compressionType='gz', cipherType='AES/GCM/NoPadding', iv='[B@ef9c620', cpuArch='arm64-v8a', backupVersionCode='8000', permissions='[]'}]}: Restore special data
06-27 22:58:11.373 10420 10452 D OpenGLRenderer: endAllActiveAnimators on 0xb400007855d4d070 (RippleDrawable) with handle 0xb400007765c9e480
06-27 22:58:11.600 10420 10500 D o@4:f   : Decryption enabled
06-27 22:58:11.676 10420 10500 D c@11:a0 : Extracting special.smsmms.json.json (filesize: 103270)
06-27 22:58:11.732 10420 10500 D h@1:g$a : Running Command: "toybox" chmod 700 "/data/user/0/com.machiav3lli.backup/cache/special.smsmms.json/special.smsmms.json.json"
06-27 22:58:11.754 10420 10500 D h@7:g$a : Command(s) "toybox" chmod 700 "/data/user/0/com.machiav3lli.backup/cache/special.smsmms.json/special.smsmms.json.json" ended with 0
06-27 22:58:11.754 10420 10500 D h@1:g$a : Running Command: "toybox" chown u0_a355:u0_a355_cache "/data/user/0/com.machiav3lli.backup/cache/special.smsmms.json/special.smsmms.json.json"
06-27 22:58:11.776 10420 10500 D h@7:g$a : Command(s) "toybox" chown u0_a355:u0_a355_cache "/data/user/0/com.machiav3lli.backup/cache/special.smsmms.json/special.smsmms.json.json" ended with 0
06-27 22:58:11.777 10420 10500 D h@1:g$a : Running Command: "toybox" touch -m -d 2022-06-26T15:41:00 "/data/user/0/com.machiav3lli.backup/cache/special.smsmms.json/special.smsmms.json.json"
06-27 22:58:11.809 10420 10500 D h@7:g$a : Command(s) "toybox" touch -m -d 2022-06-26T15:41:00 "/data/user/0/com.machiav3lli.backup/cache/special.smsmms.json/special.smsmms.json.json" ended with 0
06-27 22:58:11.809 10420 10500 D h@1:g$a : Running Command: "toybox" ls -bA1 "/data/user/0/com.machiav3lli.backup/cache/special.smsmms.json"/
06-27 22:58:11.829 10420 10500 D h@7:g$a : Command(s) "toybox" ls -bA1 "/data/user/0/com.machiav3lli.backup/cache/special.smsmms.json"/ ended with 0
06-27 22:58:11.829 10420 10500 D h@1:g$a : Running Command: "toybox" ls -bdAlZ "/data/user/0/com.machiav3lli.backup/cache/special.smsmms.json.json"
06-27 22:58:11.851 10420 10500 D h@7:g$a : Command(s) "toybox" ls -bdAlZ "/data/user/0/com.machiav3lli.backup/cache/special.smsmms.json.json" ended with 0
06-27 22:58:11.852 10420 10500 D h@1:g$a : Running Command: "toybox" mv -f "/data/user/0/com.machiav3lli.backup/cache/special.smsmms.json/special.smsmms.json.json" "/data/user/0/com.machiav3lli.backup/cache/special.smsmms.json.json" ; "toybox" chown u0_a218:u0_a218_cache "/data/user/0/com.machiav3lli.backup/cache/special.smsmms.json.json" ; chcon -R -h -v 'u:object_r:app_data_file:s0:c218,c256,c512,c768' "/data/user/0/com.machiav3lli.backup/cache/special.smsmms.json.json"
06-27 22:58:11.908 10420 10500 D h@7:g$a : Command(s) "toybox" mv -f "/data/user/0/com.machiav3lli.backup/cache/special.smsmms.json/special.smsmms.json.json" "/data/user/0/com.machiav3lli.backup/cache/special.smsmms.json.json" ; "toybox" chown u0_a218:u0_a218_cache "/data/user/0/com.machiav3lli.backup/cache/special.smsmms.json.json" ; chcon -R -h -v 'u:object_r:app_data_file:s0:c218,c256,c512,c768' "/data/user/0/com.machiav3lli.backup/cache/special.smsmms.json.json" ended with 0
06-27 22:58:11.944 10420 10500 E SqliteWrapper: Catch a SQLiteException when query: 
06-27 22:58:11.944 10420 10500 E SqliteWrapper: android.database.sqlite.SQLiteException: Can't downgrade database from version 68 to 67
06-27 22:58:11.944 10420 10500 E SqliteWrapper: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:186)
06-27 22:58:11.944 10420 10500 E SqliteWrapper: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
06-27 22:58:11.944 10420 10500 E SqliteWrapper: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
06-27 22:58:11.944 10420 10500 E SqliteWrapper: 	at android.content.ContentResolver.query(ContentResolver.java:1219)
06-27 22:58:11.944 10420 10500 E SqliteWrapper: 	at android.content.ContentResolver.query(ContentResolver.java:1151)
06-27 22:58:11.944 10420 10500 E SqliteWrapper: 	at android.content.ContentResolver.query(ContentResolver.java:1107)
06-27 22:58:11.944 10420 10500 E SqliteWrapper: 	at android.database.sqlite.SqliteWrapper.query(SqliteWrapper.java:61)
06-27 22:58:11.944 10420 10500 E SqliteWrapper: 	at android.provider.Telephony$Threads.getOrCreateThreadId(Telephony.java:2213)
06-27 22:58:11.944 10420 10500 E SqliteWrapper: 	at android.provider.Telephony$Threads.getOrCreateThreadId(Telephony.java:2189)
06-27 22:58:11.944 10420 10500 E SqliteWrapper: 	at q7.h.b(:3)
06-27 22:58:11.944 10420 10500 E SqliteWrapper: 	at q7.h.a(:2)
06-27 22:58:11.944 10420 10500 E SqliteWrapper: 	at q7.i.r(:26)
06-27 22:58:11.944 10420 10500 E SqliteWrapper: 	at q7.i.q(Unknown Source:9)
06-27 22:58:11.944 10420 10500 E SqliteWrapper: 	at y7.d.c(:16)
06-27 22:58:11.944 10420 10500 E SqliteWrapper: 	at b8.f.a(:9)
06-27 22:58:11.944 10420 10500 E SqliteWrapper: 	at b8.e$b.i(Unknown Source:33)
06-27 22:58:11.944 10420 10500 E SqliteWrapper: 	at r8.a.t(Unknown Source:8)
06-27 22:58:11.944 10420 10500 E SqliteWrapper: 	at h9.o0.run(Unknown Source:86)
06-27 22:58:11.944 10420 10500 E SqliteWrapper: 	at n9.a.E(Unknown Source:0)
06-27 22:58:11.944 10420 10500 E SqliteWrapper: 	at n9.a$a.run(:5)
06-27 22:58:11.948 10420 10500 D h@1:g$a : Running Command: "toybox" ls -bA1 "/data/user/0/com.machiav3lli.backup/cache/special.smsmms.json"/
06-27 22:58:11.967 10420 10500 D h@7:g$a : Command(s) "toybox" ls -bA1 "/data/user/0/com.machiav3lli.backup/cache/special.smsmms.json"/ ended with 0
06-27 22:58:12.003 10420 10500 D r@41:i  : Schedule{packageName=special.smsmms.json, appInfo=v7.g@62020a0, appUri=/tree/primary:OABX/document/primary:OABX/special.smsmms.json, storageStats=null, backupList=[Backup{backupDate=2022-06-26T15:41:28.573, hasApk=false, hasAppData=true, hasDevicesProtectedData=false, hasExternalData=false, hasObbData=false, hasMediaData=false, compressionType='gz', cipherType='AES/GCM/NoPadding', iv='[B@ef9c620', cpuArch='arm64-v8a', backupVersionCode='8000', permissions='[]'}]}: Uncompressed data was deleted: true
06-27 22:58:12.004 10420 10500 D c@41:d  : post-process package (to set it back to normal operation)
06-27 22:58:12.004 10420 10500 W d@6:d   : special.smsmms.json does not exist. Cannot post-process!
06-27 22:58:12.004 10420 10500 I c@45:d  : Schedule{packageName=special.smsmms.json, appInfo=v7.g@62020a0, appUri=/tree/primary:OABX/document/primary:OABX/special.smsmms.json, storageStats=null, backupList=[Backup{backupDate=2022-06-26T15:41:28.573, hasApk=false, hasAppData=true, hasDevicesProtectedData=false, hasExternalData=false, hasObbData=false, hasMediaData=false, compressionType='gz', cipherType='AES/GCM/NoPadding', iv='[B@ef9c620', cpuArch='arm64-v8a', backupVersionCode='8000', permissions='[]'}]}: Restore done: Backup{backupDate=2022-06-26T15:41:28.573, hasApk=false, hasAppData=true, hasDevicesProtectedData=false, hasExternalData=false, hasObbData=false, hasMediaData=false, compressionType='gz', cipherType='AES/GCM/NoPadding', iv='[B@ef9c620', cpuArch='arm64-v8a', backupVersionCode='8000', permissions='[]'}
06-27 22:58:12.004 10420 10500 I c@57:d  : [special.smsmms.json] Restore succeeded: false
06-27 22:58:12.005 10420 10420 D i@4:e$b$a: after do in back FINISHED--false
06-27 22:58:12.103 10420 10500 D b@11:c$c: json: {"backupVersionCode":8000,"packageName":"special.smsmms.json","packageLabel":"$ SMS/MMS JSON","versionName":"11","versionCode":30,"splitSourceDirs":[],"isSystem":true,"backupDate":"2022-06-26T15:41:28.573","hasAppData":true,"cipherType":"AES/GCM/NoPadding","iv":[-27,3,72,-101,20,-58,22,114,-53,-65,-86,102,-7,-103,17,108],"cpuArch":"arm64-v8a"}
06-27 22:58:12.171 10420 10500 D b@11:c$c: json: {"backupVersionCode":8000,"packageName":"special.smsmms.json","packageLabel":"$ SMS/MMS JSON","versionName":"11","versionCode":30,"splitSourceDirs":[],"isSystem":true,"backupDate":"2022-06-26T15:41:28.573","hasAppData":true,"cipherType":"AES/GCM/NoPadding","iv":[-27,3,72,-101,20,-58,22,114,-53,-65,-86,102,-7,-103,17,108],"cpuArch":"arm64-v8a"}
06-27 22:58:12.212 10420 10420 D l@9:HomeFragment: refreshing
06-27 22:58:12.213 10420 10420 D l@9:BatchFragment: refreshing
06-27 22:58:12.214 10420 10420 D l@9:HomeFragment: refreshing
```

</details>

**Comment by dl200010** [comment]
@hg42 I may have to adjust the calls or it may not be part of the SMS/MMS JSON. Did SqlightWrapper get updated?

@outtaspes Are you on the Telegram? If you are, then you can try the latest alpha/beta there and see if it restores.

**Comment by hg42** [comment]
@dl200010 so you are writing to a database file? or even creating it?

I just tried to backup and restore SMS in an A12 emulator and it works flawlessly.

**Comment by hg42** [comment]
this doesn't look like any database access:

```
    private fun saveSMS(context: Context, values: ContentValues, queryWhere: String) {
        // Check for duplicates
        val existsCursor = context.contentResolver.query(Telephony.Sms.CONTENT_URI, arrayOf(Telephony.Sms._ID), queryWhere, null, null)
        val exists = existsCursor?.count
        existsCursor?.close()
        if (exists == 0) {
            context.contentResolver.insert(Telephony.Sms.CONTENT_URI, values)
        }
    }

```

MMS is more complicated, but doesn't look like database, either.

**Comment by dl200010** [comment]
@hg42 It is using the provider to read and write, which does use SQL passed into the content resolver. I read/write to a file using the JsonReader/JsonWriter. It is quite possible that the custom ROM he is using actually updated the SQLite version on the system, but I don't see why simple SQL would error out like this.

**Comment by outtaspes** [comment]
> Are you on the Telegram? If you are, then you can try the latest alpha/beta there and see if it restores.

No, I am not on Telegram, but I could maybe compile it myself? Not today tho :slightly_smiling_face:

**Comment by hg42** [comment]
alternatively, you could contact me via email (see my github profile) and I could send you an apk

**Comment by outtaspes** [comment]
Okay, had a bit time and compile/tested 8.0.3-alpha1 tag and master-8bb31a8c (nice redesign btw). The result is unfortunately the same. 
With another SMS backup I had less success. There is only one that promises the same functionality and that is `com.github.tmo1.sms_ie` (F-Droid) and that just crashes on restore, however in logcat I see the same error basically.

**Comment by dl200010** [comment]
@outtaspes Than it looks to be an issue with the new ROM. I do not have said ROM for my device. NB's backup was based upon that SMS backup app. I did find the support site for the ROM you are using and asked a question about this.

**Comment by dl200010** [comment]
@outtaspes Could you save your current backup that you are wanting to restore but is being blacked by this, than try running a backup of SMS/MMS on SuperiorOS?

**Comment by outtaspes** [comment]
@dl200010 Yeah backup also doesn't work. Looked into the source in SuperiorOS and it seems the TelephonyProvider is really really old. I try to replace the provider with the LineageOS one and see if it works. I consider using LineageOS maybe, but that would be a bit of work to re-setup everything :unamused:

**Comment by dl200010** [comment]
@outtaspes You're welcome. Sorry I couldn't fix it. I still have that thread open with it's devs.

**Comment by outtaspes** [comment]
@dl200010 Okay. I replaced the old provider with the one from LineageOS and recompiled and it works. It's really just an outdated TelephonyProvider, which I didn't doubt much, but I doubt that my changes would work like that.
