### ISSUE TITLE
[Bug] Crashing

### ISSUE THREAD

**Issue by EvanCarroll** [NeoApplications/Neo-Backup#599]
The app crashes at start. This is my logcat.

```text
07-17 20:05:16.597 16381 16381 E AndroidRuntime: FATAL EXCEPTION: main
07-17 20:05:16.597 16381 16381 E AndroidRuntime: Process: com.machiav3lli.backup, PID: 16381
07-17 20:05:16.597 16381 16381 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.machiav3lli.backup.OABX: y7.g$e: 
07-17 20:05:16.597 16381 16381 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
07-17 20:05:16.597 16381 16381 E AndroidRuntime:        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
07-17 20:05:16.597 16381 16381 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
07-17 20:05:16.597 16381 16381 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
07-17 20:05:16.597 16381 16381 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
07-17 20:05:16.597 16381 16381 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
07-17 20:05:16.597 16381 16381 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-17 20:05:16.597 16381 16381 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
07-17 20:05:16.597 16381 16381 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
07-17 20:05:16.597 16381 16381 E AndroidRuntime: Caused by: y7.g$e: 
07-17 20:05:16.597 16381 16381 E AndroidRuntime:        at y7.g.<init>(:7)
07-17 20:05:16.597 16381 16381 E AndroidRuntime:        at com.machiav3lli.backup.OABX.onCreate(:1)
07-17 20:05:16.597 16381 16381 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
07-17 20:05:16.597 16381 16381 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
07-17 20:05:16.597 16381 16381 E AndroidRuntime:        ... 8 more
```

**Comment by machiav3lli** [comment]
Can you please provide more info: Version, Device, Rom, root method…

**Comment by EvanCarroll** [comment]
Actually more information on this shows it is a dupe,

```text
07-17 20:45:01.370 18019 18019 D h@7:g$a : Command(s) "/data/local/toybox" --version ended with -1                                                                            
07-17 20:45:01.370 18019 18019 D h@1:g$a : Running Command: "/data/local/toybox"                                                                                              
07-17 20:45:01.370 18019 18019 D h@7:g$a : Command(s) "/data/local/toybox" ended with -1                                                                                      
07-17 20:45:01.371 18019 18019 D h@1:g$a : Running Command: "toybox" --version                                                                                                
07-17 20:45:01.371 18019 18019 D h@7:g$a : Command(s) "toybox" --version ended with -1                                                                                        
07-17 20:45:01.371 18019 18019 D h@1:g$a : Running Command: "toybox"                                                                                                          
07-17 20:45:01.371 18019 18019 D h@7:g$a : Command(s) "toybox" ended with -1                                                                                                  
07-17 20:45:01.372 18019 18019 D <init>@7:g: No more options for utilbox. Bailing out.                                                                                        
07-17 20:45:01.372 18019 18019 D AndroidRuntime: Shutting down VM                                                                                                             
07-17 20:45:01.372 18019 18019 E AndroidRuntime: FATAL EXCEPTION: main                                                                                                        
07-17 20:45:01.372 18019 18019 E AndroidRuntime: Process: com.machiav3lli.backup, PID: 18019                                                                                  
07-17 20:45:01.372 18019 18019 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.machiav3lli.backup.OABX: y7.g$e:                                
07-17 20:45:01.372 18019 18019 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)                                         
07-17 20:45:01.372 18019 18019 E AndroidRuntime:        at android.app.ActivityThread.access$1300(ActivityThread.java:219)                                                    
07-17 20:45:01.372 18019 18019 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)                                               
07-17 20:45:01.372 18019 18019 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)                                                               
07-17 20:45:01.372 18019 18019 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)                                                                            
07-17 20:45:01.372 18019 18019 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)                                                          
07-17 20:45:01.372 18019 18019 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)                                                                     
07-17 20:45:01.372 18019 18019 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
07-17 20:45:01.372 18019 18019 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
07-17 20:45:01.372 18019 18019 E AndroidRuntime: Caused by: y7.g$e: 
07-17 20:45:01.372 18019 18019 E AndroidRuntime:        at y7.g.<init>(:7)
07-17 20:45:01.372 18019 18019 E AndroidRuntime:        at com.machiav3lli.backup.OABX.onCreate(:1)
07-17 20:45:01.372 18019 18019 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
07-17 20:45:01.372 18019 18019 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
07-17 20:45:01.372 18019 18019 E AndroidRuntime:        ... 8 more
```

LineageOS 17.1

**Comment by EvanCarroll** [comment]
@machiav3lli the problem is my toybox is in `/system/bin/toybox`

**Comment by EvanCarroll** [comment]
When I copy my toybox from `/system/bin/toybox` to `/data/local/toybox`, I get instead.

```text
07-17 20:50:30.239  5489  5489 D h@7:g$a : Command(s) "/data/local/toybox" --version ended with -1                                                                            
07-17 20:50:30.239  5489  5489 D h@1:g$a : Running Command: "/data/local/toybox"                                                                                              
07-17 20:50:30.239  5489  5489 D h@7:g$a : Command(s) "/data/local/toybox" ended with -1                                                                                      
07-17 20:50:30.240  5489  5489 D h@1:g$a : Running Command: "toybox" --version                                                                                                
07-17 20:50:30.240  5489  5489 D h@7:g$a : Command(s) "toybox" --version ended with -1                                                                                        
07-17 20:50:30.240  5489  5489 D h@1:g$a : Running Command: "toybox"                                                                                                          
07-17 20:50:30.240  5489  5489 D h@7:g$a : Command(s) "toybox" ended with -1                                                                                                  
07-17 20:50:30.240  5489  5489 D <init>@7:g: No more options for utilbox. Bailing out.                                                                                        
07-17 20:50:30.240  5489  5489 D AndroidRuntime: Shutting down VM                                                                                                             
07-17 20:50:30.240  5489  5489 E AndroidRuntime: FATAL EXCEPTION: main                                                                                                        
07-17 20:50:30.240  5489  5489 E AndroidRuntime: Process: com.machiav3lli.backup, PID: 5489                                                                                   
07-17 20:50:30.240  5489  5489 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.machiav3lli.backup.OABX: y7.g$e:                                
07-17 20:50:30.240  5489  5489 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)                                         
07-17 20:50:30.240  5489  5489 E AndroidRuntime:        at android.app.ActivityThread.access$1300(ActivityThread.java:219)                                                    
07-17 20:50:30.240  5489  5489 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)                                               
07-17 20:50:30.240  5489  5489 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)                                                               
07-17 20:50:30.240  5489  5489 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)                                                                            
07-17 20:50:30.240  5489  5489 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)                                                          
07-17 20:50:30.240  5489  5489 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)                                                                     
07-17 20:50:30.240  5489  5489 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)                                  
07-17 20:50:30.240  5489  5489 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)                                                       
07-17 20:50:30.240  5489  5489 E AndroidRuntime: Caused by: y7.g$e:                                                                                                           
07-17 20:50:30.240  5489  5489 E AndroidRuntime:        at y7.g.<init>(:7)                                                                                                    
07-17 20:50:30.240  5489  5489 E AndroidRuntime:        at com.machiav3lli.backup.OABX.onCreate(:1)                                                                           
07-17 20:50:30.240  5489  5489 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)                                     
07-17 20:50:30.240  5489  5489 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)                                         
07-17 20:50:30.240  5489  5489 E AndroidRuntime:        ... 8 more
```

**Comment by hg42** [comment]
still no answer to:
> Version, Device, Rom, root method…

in which shell did you manually execute the toybox command?

as you see NB cannot execute any of the commands.
From memory I think, the -1 means, that the command/executable cannot be found or may be some other reason, that the command cannot be executed, e.g. a problem with root (though Nyb doesn't complain, but I don't know the version of NB).

Please try toybox in a normal terminal or adb, not something like termux, which has it's own executables and environment. NB uses the normal system commands and shell.

**Comment by EvanCarroll** [comment]
Toybox was executed under `adb root`. I said the rom earlier, 

    LineageOS 17.1 / Android 10

**Comment by hg42** [comment]
`/system/bin/toybox` should be in the path.

If you copied toybox to `/data/local/toybox` and execute it in your shell, I wonder why NB cannot execute it.
There must be a difference.

NB uses root, so it should be able to access files of all users/groups.

Not sure about the selinux context. This could eventually make a difference (note, I don't know much about selinux).

The root method is still open I think. Don't you use Magisk? mount namespace isolation could also hide toybox from NB. But I would be surprised if `/system/bin/` wouldn't be accessible.
