### ISSUE TITLE
[Bug] NeoBackup Crashes when changing screen orientation

### ISSUE THREAD

**Issue by MrEngineerMind** [NeoApplications/Neo-Backup#645]
**Description**
When viewing an app's appsheet, if I rotate my device to go from portrait to landscape or visa-versa, the app will crash.

- Device: Pixel 4a
- Android Version: 10
- ROM: (AOSP, MIUI, OOS...)  Stock
- App's Version: 8.1.3

**Comment by machiav3lli** [comment]
Crash log? I can't reproduce it

**Comment by MrEngineerMind** [comment]
Config changes=20000480 {1.15 310mcc410mnc [en_US] ldltr sw320dp w605dp h291dp 540dpi nrml long hdr widecg land finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2340, 1080) mAppBounds=Rect(136, 0 - 2178, 1080) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_90} s.157}
Override config changes=20000480 {1.15 310mcc410mnc [en_US] ldltr sw320dp w605dp h291dp 540dpi nrml long hdr widecg land finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2340, 1080) mAppBounds=Rect(136, 0 - 2178, 1080) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_90} s.157} for displayId=0
Viewport [0] to add: local:19260456670010497
publishing device rotation =1 (x90deg)
adev_set_parameters: enter: rotation=90
hfp_set_parameters: enter
uid=1041(audioserver) audio@2.0-servi identical 1 line
hfp_set_parameters: enter
Reconfiguring input devices.  changes=0x00000004
Device reconfigured: id=4, name='fts', size 1080x2340, orientation 1, mode 1, display id 0
disable<e i a s b h r c s > disable2<q i n >
systemKeyboardHeightRatio:1.200000; userKeyboardHeightRatio:0.900000.
Shutting down VM
FATAL EXCEPTION: main
Process: com.machiav3lli.backup, PID: 8683
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.machiav3lli.backup/com.machiav3lli.backup.activities.MainActivityX}: androidx.fragment.app.n$d: Unable to instantiate fragment com.machiav3lli.backup.fragments.AppSheet: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5279)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5187)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: androidx.fragment.app.n$d: Unable to instantiate fragment com.machiav3lli.backup.fragments.AppSheet: could not find Fragment constructor
	at androidx.fragment.app.d0$d.a(Unknown Source:58)
	at androidx.fragment.app.i0.a(Unknown Source:2)
	at androidx.fragment.app.j0.<init>(Unknown Source:13)
	at androidx.fragment.app.d0.Y(Unknown Source:274)
	at androidx.fragment.app.d0.c(Unknown Source:169)
	at androidx.fragment.app.q.a(Unknown Source:9)
	at androidx.activity.ComponentActivity.onCreate(Unknown Source:27)
	at androidx.fragment.app.r.onCreate(Unknown Source:0)
	at com.machiav3lli.backup.activities.MainActivityX.onCreate(Unknown Source:15)
	at android.app.Activity.performCreate(Activity.java:7825)
	at android.app.Activity.performCreate(Activity.java:7814)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 13 more
Caused by: java.lang.NoSuchMethodException: com.machiav3lli.backup.fragments.AppSheet.<init> []
	at java.lang.Class.getConstructor0(Class.java:2332)
	at java.lang.Class.getConstructor(Class.java:1728)
	at androidx.fragment.app.d0$d.a(Unknown Source:23)
	... 25 more
close(): Successfully wrote DLAM properties file.
  Force finishing activity com.machiav3lli.backup/.activities.MainActivityX
systemKeyboardHeightRatio:1.200000; userKeyboardHeightRatio:0.900000.
Showing crash dialog for package com.machiav3lli.backup u0
Invalid ID 0x00000000.
add tag=data_app_crash isTagEnabled=true flags=0x2
onReceive() : Action = android.intent.action.CONFIGURATION_CHANGED
Get device mode by ui mode:1 and smallestScreenWidthDp:320

**Comment by Smutley** [comment]
I also experience this crashing issue on my Pixel 8, as well as on two Xiamoi phones. Neo Backup will simply exit when device is tilted towards landscape mode. 

Three different Android OS: MIUI 10, Lineage OS 13, and stock Pixel OS on Pixel 8.
