### ISSUE TITLE
[Bug] Restored app keeps crashing

### ISSUE THREAD

**Issue by kolaente** [NeoApplications/Neo-Backup#680]
**Description**
I've restored [this app](https://play.google.com/store/apps/details?id=de.deutschlandfunk.dlfaudiothek&amp;hl=de) with data from a backup and now it just keeps crashing. The wired thing is, it keeps doing that even after I've reinstalled it. I assume there are some files which have been restored but are not properly removed when uninstalling.

I took the backup on OxygenOS (Android 11) and restored it on Lineage OS 19 (Android 12).

This may be similar to https://github.com/NeoApplications/Neo-Backup/issues/247 but iirc the app does not use the android keystore.

**Steps To Reproduce**

1. Install the app
2. Change some settings so that there's data to back up
3. Make a backup with app data
4. Switch over to Lineage os
5. Restore the app from backup
6. App keeps crashing

**Expected behavior**
App restored properly, no crashes

**Logs**

Here are the logs of what happens when opening the app (when it crashes):

```
FATAL EXCEPTION: main
Process: de.deutschlandfunk.dlfaudiothek, PID: 2002
java.lang.RuntimeException: Unable to create service de.deutschlandradio.common.di.DlfAudioService: java.lang.RuntimeException: b0.d.a.c.c.r.b0: com.google.android.gms.dynamite.DynamiteModule$a: No acceptable module found. Local version is 0 and remote version is 0.
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4567)
	at android.app.ActivityThread.access$1700(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.RuntimeException: b0.d.a.c.c.r.b0: com.google.android.gms.dynamite.DynamiteModule$a: No acceptable module found. Local version is 0 and remote version is 0.
	at b0.d.a.c.c.r.b.b(SourceFile:8)
	at b.a.b.a.x.<init>(SourceFile:43)
	at b.a.b.d.onCreate(SourceFile:18)
	at de.deutschlandradio.common.di.DlfAudioService.onCreate(SourceFile:2)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4554)
	... 9 more
Caused by: b0.d.a.c.c.r.b0: com.google.android.gms.dynamite.DynamiteModule$a: No acceptable module found. Local version is 0 and remote version is 0.
	at b0.d.a.c.h.b.m4.a(SourceFile:12)
	at b0.d.a.c.c.r.b.<init>(SourceFile:20)
	at b0.d.a.c.c.r.b.b(SourceFile:6)
	... 13 more
Caused by: com.google.android.gms.dynamite.DynamiteModule$a: No acceptable module found. Local version is 0 and remote version is 0.
	at com.google.android.gms.dynamite.DynamiteModule.a(SourceFile:35)
	at b0.d.a.c.h.b.m4.a(SourceFile:2)
	... 15 more
```

**System Information(please complete the following information):**

- Device: Oneplus 6
- Android Version: 12
- ROM: Lineage OS
- App's Version: 8.2.0

**Comment by machiav3lli** [comment]
It can be that you moved from a ROM wiith Gapps to one without. If true then it's the issue. The app is trying to call a google API but failing, as no gsf (maybe also not even microG?) is installed
